name: Dummy jobs 2

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  merge_group:
    branches: [ dev ]
    
jobs:
  success:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
